### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [akorotkov/pgsphere#16]
I don't see any git version tags in repo.
Do you have any plans to make new release? :)

**Comment by esabol** [comment]
https://github.com/postgrespro/pgsphere/ seems to be the most active pgsphere repo these days, fwiw.

**Comment by kloczek** [comment]
Moment so this os not main repo? 🤔 

Nevertheless none of the repos have version tags ..

**Comment by esabol** [comment]
There are at least 6 pgsphere repos. It's confusing. I just pointed you to the one that I feel is currently active. This repo has not had any commits in 4 years.

**Comment by kloczek** [comment]
THx to let me know 😋 
Closing this ticket 👍

**Comment by akorotkov** [comment]
Hi guys,
Yes, I don't have time to maintain this repo. I'm sorry that existence of this repo could lead to a confusion.
I would be happy to delete it. I just want to be sure there is no useful commits, which could be moved to another repo.

**Comment by kloczek** [comment]
It would be IMO good to pass to new maintainer pypi entry 😄

**Comment by esabol** [comment]
> Yes, I don't have time to maintain this repo. I'm sorry that existence of this repo could lead to a confusion.
> I would be happy to delete it. I just want to be sure there is no useful commits, which could be moved to another repo.

Yes, please don't delete it. The history is important, and there is at least one PR that I still want to see merged into some pgsphere repo. Thank you for all that you've done!

**Comment by aoberto** [comment]
thanks for sharing, I was using this repo: https://github.com/credativ/pgsphere
